title: diary
description: "ramblings of an anxious software engineer"
theme: jekyll-theme-hacker

collections:
  authors:
  output: true
  
excerpt_separator: <!--more-->

baseurl: /
paginate: 3
paginate_path: /page/:num/

future: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
