title: diary
description: "ramblings of an anxious software engineer"
theme: jekyll-theme-hacker

collections:
  authors: otvv
  output: true

baseurl: /
paginate: 3
paginate_path: /page/:num/

future: true
