title: diary/
description: "ramblings of an anxious software engineer who happens to love cars"
theme: jekyll-theme-hacker

paginate: 3
paginate_path: /page/:num/

baseurl: /
future: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
